name = "LEFEM"
uuid = "bbb4a789-0fc6-4acc-8eae-7f825c1dd415"
authors = ["Hetao Z."]
version = "0.1.0"

[compat]
julia = "1.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
